title: ThePurpleAndRed
description: ThePurpleAndRed is a private social application for users to connect with eachother and use custom services.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions